snowflake:
  target: "{{ env_var('OS_ENV') }}"
  outputs:
    dev:
      type: snowflake
      threads: 1
      account: "pitchbook"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: BI_ELT
      warehouse: LOADING_WH
      database: BASE_DEV
      schema: MIERS
    prod:
      type: snowflake
      threads: 1
      account: "pitchbook"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: BI_ELT
      warehouse: LOADING_WH
      database: BASE
      schema: MIERS
