WITH source_data AS (
    SELECT
       SPLIT_PART(DOC_ID_CONTRIBUTOR,'_', -2) as Doc_ID,
       E_MAIL AS Email,
       TRY_TO_TIMESTAMP(datetime_read, 'DD-MON-YYYY HH24:MI') as Date_Time_Read,
       PLATFORM,
       Reader_ID_FactSet as Reader_ID,
       Reader_name,
       Phone,
       Parent_Firm_ID_FactSet as Parent_Firm_ID,
       Parent_Firm_name,
       Firm_ID_FactSet as Firm_ID,
       Firm_name,
       Firm_Address,
       Firm_City,
       Firm_State,
       Firm_Country,
       Doc_ID_contributor as Raw_Doc_ID,
       Doc_ID_FactSet,
       Readership_Event_ID_FactSet as Readership_Event_ID,
       TRY_TO_TIMESTAMP(datetime_published, 'DD-MON-YYYY HH24:MI') as Date_Time_Published,
       TRY_TO_TIMESTAMP(datetime_received, 'DD-MON-YYYY HH24:MI') as Date_Time_Received,
       Report_title,
       Primary_issuer_Ticker,
       Primary_issuer_name,
       Primary_analyst_code_contributor,
       Primary_analyst_code_FactSet,
       Primary_analyst_name,
       Number_of_pages_in_report,
       Report_Purpose ,
       Report_Focus,
       Asset_Class,
       Asset_Type,
       Primary_Industry_Code_FactSet,
       Primary_Industry_Name_FactSet,
       Security_Type,
       Discipline,
       Research_Approach,
       Periodicity,
       Region,
       Country,
       Compilation_Indicator,
       LAST_UPDATED_DATETIME as LAST_UPDATED,
       -- Adding row_num to avoid the same record from different files upstream being inserted multiple times into base
       ROW_NUMBER() OVER (PARTITION BY Readership_Event_ID_FactSet, Reader_ID_FactSet, DOC_ID_CONTRIBUTOR, DATETIME_READ ORDER BY LAST_UPDATED_DATETIME DESC) AS row_num
    FROM {{ env_var('SNOWFLAKE_DATABASE') }}.MIERS.FACTSET
)

SELECT Doc_ID,
       Email,
       Date_Time_Read,
       PLATFORM,
       Reader_ID,
       Reader_name,
       Phone,
       Parent_Firm_ID,
       Parent_Firm_name,
       Firm_ID,
       Firm_name,
       Firm_Address,
       Firm_City,
       Firm_State,
       Firm_Country,
       Raw_Doc_ID,
       Doc_ID_FactSet,
       Readership_Event_ID,
       Date_Time_Published,
       Date_Time_Received,
       Report_title,
       Primary_issuer_Ticker,
       Primary_issuer_name,
       Primary_analyst_code_contributor,
       Primary_analyst_code_FactSet,
       Primary_analyst_name,
       Number_of_pages_in_report,
       Report_Purpose ,
       Report_Focus,
       Asset_Class,
       Asset_Type,
       Primary_Industry_Code_FactSet,
       Primary_Industry_Name_FactSet,
       Security_Type,
       Discipline,
       Research_Approach,
       Periodicity,
       Region,
       Country,
       Compilation_Indicator,
       LAST_UPDATED
FROM source_data
-- Don't add ; here to close it out ever, it gives error instead
WHERE row_num = 1